spring:
    application:
        name: demo
    datasource:
        driverClassName: org.h2.Driver
        username: sa
        password:
        url: jdbc:h2:mem:testdb
    h2:
        console:
            enabled: true
            path: /h2
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        generate-ddl: true
        hibernate:
            ddl-auto: create-drop
springdoc:
    swagger-ui:
        disable-swagger-default-url: true
        operationsSorter: method

